import * as cheerio from "cheerio";

const STUDENT_PORTAL_BASE_URL = "https://sp.srmist.edu.in";
const LOGIN_PAGE_URL =
    `${STUDENT_PORTAL_BASE_URL}/srmiststudentportal/students/loginManager/youLogin.jsp`;
const LOGIN_URL =
    `${STUDENT_PORTAL_BASE_URL}/srmiststudentportal/LoginServlet`;
const ATTENDANCE_URL =
    `${STUDENT_PORTAL_BASE_URL}/srmiststudentportal/students/report/studentAttendanceDetails.jsp`;

const DEFAULT_HEADERS = {
    "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
        "(KHTML, like Gecko) Chrome/153.0.0.0 Safari/537.36",
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
};

export interface StudentPortalCaptcha {
    type: "STUDENT_PORTAL_CAPTCHA_REQUIRED";
    image: string;
}

export class StudentPortalClient {
    private cookies = new Map<string, string>();

    private captureCookies(response: Response) {
        const headers = response.headers as any;

        let setCookies: string[] = [];

        if (typeof headers.getSetCookie === "function") {
            setCookies = headers.getSetCookie() || [];
        } else {
            const raw = response.headers.get("set-cookie");
            if (raw) {
                setCookies = raw.split(/,(?=\s*[A-Za-z0-9_-]+=)/);
            }
        }

        for (const header of setCookies) {
            const [cookiePart] = header.split(";");
            const separator = cookiePart.indexOf("=");

            if (separator < 1) continue;

            const name = cookiePart.slice(0, separator).trim();
            const value = cookiePart.slice(separator + 1).trim();

            this.cookies.set(name, value);
        }
    }

    private cookieHeader(): string {
        return Array.from(this.cookies.entries())
            .map(([name, value]) => `${name}=${value}`)
            .join("; ");
    }

    private async request(
        url: string,
        init: RequestInit = {},
    ): Promise<Response> {
        const headers = new Headers(DEFAULT_HEADERS);

        if (init.headers) {
            new Headers(init.headers).forEach((value, key) => {
                headers.set(key, value);
            });
        }

        const cookies = this.cookieHeader();

        if (cookies) {
            headers.set("Cookie", cookies);
        }

        const response = await fetch(url, {
            ...init,
            headers,
        });

        this.captureCookies(response);

        return response;
    }

    async initialize(): Promise<string> {
        const response = await this.request(LOGIN_PAGE_URL);

        if (!response.ok) {
            throw new Error(
                `Student Portal login page failed: HTTP ${response.status}`,
            );
        }

        return await response.text();
    }

    async getCaptchaImage(): Promise<string> {
        /*
         * The CAPTCHA URL is generated by the Student Portal.
         * We first inspect the login page for its CAPTCHA reference.
         */
        const html = await this.initialize();
        const $ = cheerio.load(html);

        const captchaImg = $("img")
            .filter((_, element) => {
                const src = ($(element).attr("src") || "").toLowerCase();
                const id = ($(element).attr("id") || "").toLowerCase();
                const alt = ($(element).attr("alt") || "").toLowerCase();

                return (
                    src.includes("captcha") ||
                    id.includes("captcha") ||
                    alt.includes("captcha")
                );
            })
            .first();

        if (!captchaImg.length) {
            throw new Error("Could not find Student Portal CAPTCHA image.");
        }

        const src = captchaImg.attr("src");

        if (!src) {
            throw new Error("Student Portal CAPTCHA image has no source.");
        }

        return new URL(src, STUDENT_PORTAL_BASE_URL).toString();
    }

    async login(
        username: string,
        password: string,
        captcha: string,
        telemetryPayload = "",
    ): Promise<boolean> {
        const payload = new URLSearchParams();

        payload.set("username", username);
        payload.set("password", password);
        payload.set("ph_bec7c769", "");
        payload.set("captcha", captcha);
        payload.set("fpPayload", "");
        payload.set("fpToken", "");
        payload.set("telemetryPayload", telemetryPayload);
        payload.set("dtoken_265495", "bmkudWRlLnRzaW1ycy5wcw==");
        payload.set("cptoken_ec7f17", "NTgzNDU2NDA=");
        payload.set("dtoken_265495", "bmkudWRlLnRzaW1ycy5wcw==");

        const response = await this.request(LOGIN_URL, {
            method: "POST",
            headers: {
                "Content-Type": "application/x-www-form-urlencoded",
                Origin: STUDENT_PORTAL_BASE_URL,
                Referer: LOGIN_PAGE_URL,
            },
            body: payload,
            redirect: "manual",
        });

        const text = await response.text();

        /*
         * A successful login should establish a JSESSIONID.
         */
        if (this.cookies.has("JSESSIONID")) {
            return true;
        }

        console.error(
            "[StudentPortal] Login failed:",
            response.status,
            text.slice(0, 500),
        );

        return false;
    }

    async fetchAttendance(): Promise<string> {
        const payload = new URLSearchParams();

        payload.set("iden", "9");
        payload.set("filter", "");
        payload.set("hdnFormDetails", "1");
        payload.set("csrfPreventionSalt", "");

        const response = await this.request(ATTENDANCE_URL, {
            method: "POST",
            headers: {
                "Content-Type":
                    "application/x-www-form-urlencoded; charset=UTF-8",
                Accept: "text/html, */*; q=0.01",
                Origin: STUDENT_PORTAL_BASE_URL,
                Referer:
                    `${STUDENT_PORTAL_BASE_URL}/srmiststudentportal/students/template/HRDSystem.jsp`,
                "X-Requested-With": "XMLHttpRequest",
            },
            body: payload,
        });

        if (!response.ok) {
            throw new Error(
                `Student Portal attendance request failed: HTTP ${response.status}`,
            );
        }

        return await response.text();
    }

    getCookieObject(): Record<string, string> {
        return Object.fromEntries(this.cookies);
    }
}